### ISSUE TITLE
units spawn time

### ISSUE THREAD

**Issue by konstvest** [leszekd25/spellforce_data_editor#12]
Please tell me if it is possible to change the unit's spawn time?
For example, units of the elven army are spawned several times faster than the troll army. Some troll units are spawned so long that you can have time to go to lunch.

**Comment by konstvest** [comment]
any feedback?

**Comment by leszekd25** [comment]
Ah, sorry, I got a lot on my head and don't check github threads frequently
Unit spawn times depend on two things:
1) how many resources does the unit cost
2) how many army buildings (the ones occupied by workers, so for example, archery hall doesn't count) do you have
Other than that, I'm pretty sure it can't be changed

**Comment by konstvest** [comment]
Thanks a lot!!!!
It's very useful for me and my friends. We have been playing for many years and still did not know about the second point.
Do you know if all resources have the same effect on spawn time? for example, 50 iron + 50 wood equals 100 araya?

**Comment by leszekd25** [comment]
I don't know for sure, but I think there's no difference between resources in this regard

**Comment by konstvest** [comment]
Ok, thanks. Good luck in the future development :)
